/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  sym_operator_multiply = 6,
  sym_operator_divide = 7,
  sym_operator_modulo = 8,
  sym_operator_add = 9,
  sym_operator_subtract = 10,
  sym_operator_equal = 11,
  sym_operator_not_equal = 12,
  sym_operator_less_than = 13,
  sym_operator_greater_than = 14,
  sym_operator_less_equal = 15,
  sym_operator_greater_equal = 16,
  sym_operator_and = 17,
  sym_operator_or = 18,
  sym_assign_constant = 19,
  sym_assign_variable = 20,
  sym_number_binary = 21,
  sym_number_octal = 22,
  sym_number_decimal = 23,
  sym_number_hex = 24,
  sym_escape = 25,
  sym_string_single_quoted_unescaped_string = 26,
  sym_string_double_quoted_unescaped_string = 27,
  anon_sym_SQUOTE = 28,
  anon_sym_DQUOTE = 29,
  sym_numbers_zero = 30,
  sym_booleans_false = 31,
  sym_booleans_true = 32,
  sym_identifier = 33,
  sym_source_file = 34,
  sym_source = 35,
  sym_statement = 36,
  sym__expression = 37,
  sym_parenthesize = 38,
  sym_multiplicative = 39,
  sym_additive = 40,
  sym_comparison = 41,
  sym_logical = 42,
  sym_assign = 43,
  sym__number = 44,
  sym_string_single_quoted = 45,
  sym_string_double_quoted = 46,
  sym__string = 47,
  sym_numbers = 48,
  sym_booleans = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_string_single_quoted_repeat1 = 51,
  aux_sym_string_double_quoted_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_operator_multiply] = "multiply",
  [sym_operator_divide] = "divide",
  [sym_operator_modulo] = "modulo",
  [sym_operator_add] = "add",
  [sym_operator_subtract] = "subtract",
  [sym_operator_equal] = "equal",
  [sym_operator_not_equal] = "not_equal",
  [sym_operator_less_than] = "less_than",
  [sym_operator_greater_than] = "greater_than",
  [sym_operator_less_equal] = "less_equal",
  [sym_operator_greater_equal] = "greater_equal",
  [sym_operator_and] = "and",
  [sym_operator_or] = "or",
  [sym_assign_constant] = "constant",
  [sym_assign_variable] = "variable",
  [sym_number_binary] = "binary",
  [sym_number_octal] = "octal",
  [sym_number_decimal] = "decimal",
  [sym_number_hex] = "hex",
  [sym_escape] = "escape",
  [sym_string_single_quoted_unescaped_string] = "string",
  [sym_string_double_quoted_unescaped_string] = "string",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_numbers_zero] = "zero",
  [sym_booleans_false] = "false",
  [sym_booleans_true] = "true",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_source] = "source",
  [sym_statement] = "statement",
  [sym__expression] = "_expression",
  [sym_parenthesize] = "parenthesize",
  [sym_multiplicative] = "multiplicative",
  [sym_additive] = "additive",
  [sym_comparison] = "comparison",
  [sym_logical] = "logical",
  [sym_assign] = "assign",
  [sym__number] = "_number",
  [sym_string_single_quoted] = "single_quoted",
  [sym_string_double_quoted] = "double_quoted",
  [sym__string] = "_string",
  [sym_numbers] = "numbers",
  [sym_booleans] = "booleans",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_single_quoted_repeat1] = "string_single_quoted_repeat1",
  [aux_sym_string_double_quoted_repeat1] = "string_double_quoted_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_operator_multiply] = sym_operator_multiply,
  [sym_operator_divide] = sym_operator_divide,
  [sym_operator_modulo] = sym_operator_modulo,
  [sym_operator_add] = sym_operator_add,
  [sym_operator_subtract] = sym_operator_subtract,
  [sym_operator_equal] = sym_operator_equal,
  [sym_operator_not_equal] = sym_operator_not_equal,
  [sym_operator_less_than] = sym_operator_less_than,
  [sym_operator_greater_than] = sym_operator_greater_than,
  [sym_operator_less_equal] = sym_operator_less_equal,
  [sym_operator_greater_equal] = sym_operator_greater_equal,
  [sym_operator_and] = sym_operator_and,
  [sym_operator_or] = sym_operator_or,
  [sym_assign_constant] = sym_assign_constant,
  [sym_assign_variable] = sym_assign_variable,
  [sym_number_binary] = sym_number_binary,
  [sym_number_octal] = sym_number_octal,
  [sym_number_decimal] = sym_number_decimal,
  [sym_number_hex] = sym_number_hex,
  [sym_escape] = sym_escape,
  [sym_string_single_quoted_unescaped_string] = sym_string_single_quoted_unescaped_string,
  [sym_string_double_quoted_unescaped_string] = sym_string_single_quoted_unescaped_string,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_numbers_zero] = sym_numbers_zero,
  [sym_booleans_false] = sym_booleans_false,
  [sym_booleans_true] = sym_booleans_true,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_source] = sym_source,
  [sym_statement] = sym_statement,
  [sym__expression] = sym__expression,
  [sym_parenthesize] = sym_parenthesize,
  [sym_multiplicative] = sym_multiplicative,
  [sym_additive] = sym_additive,
  [sym_comparison] = sym_comparison,
  [sym_logical] = sym_logical,
  [sym_assign] = sym_assign,
  [sym__number] = sym__number,
  [sym_string_single_quoted] = sym_string_single_quoted,
  [sym_string_double_quoted] = sym_string_double_quoted,
  [sym__string] = sym__string,
  [sym_numbers] = sym_numbers,
  [sym_booleans] = sym_booleans,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_single_quoted_repeat1] = aux_sym_string_single_quoted_repeat1,
  [aux_sym_string_double_quoted_repeat1] = aux_sym_string_double_quoted_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_operator_multiply] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_divide] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_add] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_subtract] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_not_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_less_than] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_greater_than] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_less_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_greater_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_and] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_or] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_number_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_number_octal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_hex] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_string_single_quoted_unescaped_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_double_quoted_unescaped_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_numbers_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_booleans_false] = {
    .visible = true,
    .named = true,
  },
  [sym_booleans_true] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesize] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicative] = {
    .visible = true,
    .named = true,
  },
  [sym_additive] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_logical] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_string_single_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_string_double_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym_numbers] = {
    .visible = true,
    .named = true,
  },
  [sym_booleans] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_single_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_double_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 6,
        '"', 50,
        '%', 24,
        '&', 3,
        '\'', 49,
        '(', 20,
        ')', 21,
        '*', 22,
        '+', 25,
        '-', 26,
        '/', 23,
        '0', 51,
        ':', 35,
        ';', 17,
        '<', 29,
        '=', 36,
        '>', 30,
        '\\', 7,
        'f', 54,
        't', 58,
        '{', 18,
        '|', 9,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(14);
      if (lookahead == '\r' ||
          lookahead == '?') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(44);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '|') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 6,
        '"', 50,
        '%', 24,
        '&', 3,
        '\'', 49,
        '(', 20,
        ')', 21,
        '*', 22,
        '+', 25,
        '-', 26,
        '/', 23,
        '0', 51,
        ':', 35,
        ';', 17,
        '<', 29,
        '=', 36,
        '>', 30,
        'f', 54,
        't', 58,
        '{', 18,
        '|', 9,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_operator_multiply);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_operator_divide);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_operator_modulo);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_operator_add);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_operator_subtract);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_operator_equal);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_operator_not_equal);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_operator_less_than);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operator_greater_than);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_operator_less_equal);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_operator_greater_equal);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_operator_and);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_operator_or);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_assign_constant);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_assign_variable);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number_binary);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(37);
      if (('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number_octal);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_escape);
      if (lookahead == '\n' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_string_single_quoted_unescaped_string);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_string_single_quoted_unescaped_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_string_double_quoted_unescaped_string);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_string_double_quoted_unescaped_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_numbers_zero);
      ADVANCE_MAP(
        'B', 61,
        'b', 61,
        'D', 63,
        'd', 63,
        'O', 62,
        'o', 62,
        'X', 64,
        'x', 64,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_booleans_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_booleans_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(37);
      if (('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_operator_multiply] = ACTIONS(1),
    [sym_operator_divide] = ACTIONS(1),
    [sym_operator_modulo] = ACTIONS(1),
    [sym_operator_add] = ACTIONS(1),
    [sym_operator_subtract] = ACTIONS(1),
    [sym_operator_equal] = ACTIONS(1),
    [sym_operator_not_equal] = ACTIONS(1),
    [sym_operator_less_than] = ACTIONS(1),
    [sym_operator_greater_than] = ACTIONS(1),
    [sym_operator_less_equal] = ACTIONS(1),
    [sym_operator_greater_equal] = ACTIONS(1),
    [sym_operator_and] = ACTIONS(1),
    [sym_operator_or] = ACTIONS(1),
    [sym_assign_constant] = ACTIONS(1),
    [sym_assign_variable] = ACTIONS(1),
    [sym_number_binary] = ACTIONS(1),
    [sym_number_octal] = ACTIONS(1),
    [sym_number_decimal] = ACTIONS(1),
    [sym_number_hex] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_numbers_zero] = ACTIONS(1),
    [sym_booleans_false] = ACTIONS(1),
    [sym_booleans_true] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(42),
    [sym_source] = STATE(31),
    [sym_statement] = STATE(43),
    [sym__expression] = STATE(31),
    [sym_parenthesize] = STATE(31),
    [sym_multiplicative] = STATE(31),
    [sym_additive] = STATE(31),
    [sym_comparison] = STATE(31),
    [sym_logical] = STATE(31),
    [sym_assign] = STATE(31),
    [sym__number] = STATE(31),
    [sym_string_single_quoted] = STATE(31),
    [sym_string_double_quoted] = STATE(31),
    [sym__string] = STATE(31),
    [sym_numbers] = STATE(31),
    [sym_booleans] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(11),
    [sym_number_octal] = ACTIONS(11),
    [sym_number_decimal] = ACTIONS(11),
    [sym_number_hex] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_source] = STATE(31),
    [sym_statement] = STATE(43),
    [sym__expression] = STATE(31),
    [sym_parenthesize] = STATE(31),
    [sym_multiplicative] = STATE(31),
    [sym_additive] = STATE(31),
    [sym_comparison] = STATE(31),
    [sym_logical] = STATE(31),
    [sym_assign] = STATE(31),
    [sym__number] = STATE(31),
    [sym_string_single_quoted] = STATE(31),
    [sym_string_double_quoted] = STATE(31),
    [sym__string] = STATE(31),
    [sym_numbers] = STATE(31),
    [sym_booleans] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(26),
    [sym_operator_add] = ACTIONS(29),
    [sym_operator_subtract] = ACTIONS(29),
    [sym_number_binary] = ACTIONS(32),
    [sym_number_octal] = ACTIONS(32),
    [sym_number_decimal] = ACTIONS(32),
    [sym_number_hex] = ACTIONS(32),
    [anon_sym_SQUOTE] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(38),
    [sym_numbers_zero] = ACTIONS(41),
    [sym_booleans_false] = ACTIONS(44),
    [sym_booleans_true] = ACTIONS(44),
    [sym_identifier] = ACTIONS(32),
  },
  [STATE(3)] = {
    [sym_source] = STATE(31),
    [sym_statement] = STATE(40),
    [sym__expression] = STATE(31),
    [sym_parenthesize] = STATE(31),
    [sym_multiplicative] = STATE(31),
    [sym_additive] = STATE(31),
    [sym_comparison] = STATE(31),
    [sym_logical] = STATE(31),
    [sym_assign] = STATE(31),
    [sym__number] = STATE(31),
    [sym_string_single_quoted] = STATE(31),
    [sym_string_double_quoted] = STATE(31),
    [sym__string] = STATE(31),
    [sym_numbers] = STATE(31),
    [sym_booleans] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(11),
    [sym_number_octal] = ACTIONS(11),
    [sym_number_decimal] = ACTIONS(11),
    [sym_number_hex] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(4)] = {
    [sym_source] = STATE(31),
    [sym_statement] = STATE(41),
    [sym__expression] = STATE(31),
    [sym_parenthesize] = STATE(31),
    [sym_multiplicative] = STATE(31),
    [sym_additive] = STATE(31),
    [sym_comparison] = STATE(31),
    [sym_logical] = STATE(31),
    [sym_assign] = STATE(31),
    [sym__number] = STATE(31),
    [sym_string_single_quoted] = STATE(31),
    [sym_string_double_quoted] = STATE(31),
    [sym__string] = STATE(31),
    [sym_numbers] = STATE(31),
    [sym_booleans] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(11),
    [sym_number_octal] = ACTIONS(11),
    [sym_number_decimal] = ACTIONS(11),
    [sym_number_hex] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym_source] = STATE(31),
    [sym_statement] = STATE(43),
    [sym__expression] = STATE(31),
    [sym_parenthesize] = STATE(31),
    [sym_multiplicative] = STATE(31),
    [sym_additive] = STATE(31),
    [sym_comparison] = STATE(31),
    [sym_logical] = STATE(31),
    [sym_assign] = STATE(31),
    [sym__number] = STATE(31),
    [sym_string_single_quoted] = STATE(31),
    [sym_string_double_quoted] = STATE(31),
    [sym__string] = STATE(31),
    [sym_numbers] = STATE(31),
    [sym_booleans] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(11),
    [sym_number_octal] = ACTIONS(11),
    [sym_number_decimal] = ACTIONS(11),
    [sym_number_hex] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(6)] = {
    [sym_source] = STATE(33),
    [sym__expression] = STATE(33),
    [sym_parenthesize] = STATE(33),
    [sym_multiplicative] = STATE(33),
    [sym_additive] = STATE(33),
    [sym_comparison] = STATE(33),
    [sym_logical] = STATE(33),
    [sym_assign] = STATE(33),
    [sym__number] = STATE(33),
    [sym_string_single_quoted] = STATE(33),
    [sym_string_double_quoted] = STATE(33),
    [sym__string] = STATE(33),
    [sym_numbers] = STATE(33),
    [sym_booleans] = STATE(33),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(53),
    [sym_number_octal] = ACTIONS(53),
    [sym_number_decimal] = ACTIONS(53),
    [sym_number_hex] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(53),
  },
  [STATE(7)] = {
    [sym_source] = STATE(26),
    [sym__expression] = STATE(26),
    [sym_parenthesize] = STATE(26),
    [sym_multiplicative] = STATE(26),
    [sym_additive] = STATE(26),
    [sym_comparison] = STATE(26),
    [sym_logical] = STATE(26),
    [sym_assign] = STATE(26),
    [sym__number] = STATE(26),
    [sym_string_single_quoted] = STATE(26),
    [sym_string_double_quoted] = STATE(26),
    [sym__string] = STATE(26),
    [sym_numbers] = STATE(26),
    [sym_booleans] = STATE(26),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(55),
    [sym_number_octal] = ACTIONS(55),
    [sym_number_decimal] = ACTIONS(55),
    [sym_number_hex] = ACTIONS(55),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(55),
  },
  [STATE(8)] = {
    [sym_source] = STATE(22),
    [sym__expression] = STATE(22),
    [sym_parenthesize] = STATE(22),
    [sym_multiplicative] = STATE(22),
    [sym_additive] = STATE(22),
    [sym_comparison] = STATE(22),
    [sym_logical] = STATE(22),
    [sym_assign] = STATE(22),
    [sym__number] = STATE(22),
    [sym_string_single_quoted] = STATE(22),
    [sym_string_double_quoted] = STATE(22),
    [sym__string] = STATE(22),
    [sym_numbers] = STATE(22),
    [sym_booleans] = STATE(22),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(57),
    [sym_number_octal] = ACTIONS(57),
    [sym_number_decimal] = ACTIONS(57),
    [sym_number_hex] = ACTIONS(57),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(57),
  },
  [STATE(9)] = {
    [sym_source] = STATE(17),
    [sym__expression] = STATE(17),
    [sym_parenthesize] = STATE(17),
    [sym_multiplicative] = STATE(17),
    [sym_additive] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assign] = STATE(17),
    [sym__number] = STATE(17),
    [sym_string_single_quoted] = STATE(17),
    [sym_string_double_quoted] = STATE(17),
    [sym__string] = STATE(17),
    [sym_numbers] = STATE(17),
    [sym_booleans] = STATE(17),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(59),
    [sym_number_octal] = ACTIONS(59),
    [sym_number_decimal] = ACTIONS(59),
    [sym_number_hex] = ACTIONS(59),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(59),
  },
  [STATE(10)] = {
    [sym_source] = STATE(25),
    [sym__expression] = STATE(25),
    [sym_parenthesize] = STATE(25),
    [sym_multiplicative] = STATE(25),
    [sym_additive] = STATE(25),
    [sym_comparison] = STATE(25),
    [sym_logical] = STATE(25),
    [sym_assign] = STATE(25),
    [sym__number] = STATE(25),
    [sym_string_single_quoted] = STATE(25),
    [sym_string_double_quoted] = STATE(25),
    [sym__string] = STATE(25),
    [sym_numbers] = STATE(25),
    [sym_booleans] = STATE(25),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(61),
    [sym_number_octal] = ACTIONS(61),
    [sym_number_decimal] = ACTIONS(61),
    [sym_number_hex] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(61),
  },
  [STATE(11)] = {
    [sym_source] = STATE(28),
    [sym__expression] = STATE(28),
    [sym_parenthesize] = STATE(28),
    [sym_multiplicative] = STATE(28),
    [sym_additive] = STATE(28),
    [sym_comparison] = STATE(28),
    [sym_logical] = STATE(28),
    [sym_assign] = STATE(28),
    [sym__number] = STATE(28),
    [sym_string_single_quoted] = STATE(28),
    [sym_string_double_quoted] = STATE(28),
    [sym__string] = STATE(28),
    [sym_numbers] = STATE(28),
    [sym_booleans] = STATE(28),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(63),
    [sym_number_octal] = ACTIONS(63),
    [sym_number_decimal] = ACTIONS(63),
    [sym_number_hex] = ACTIONS(63),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(63),
  },
  [STATE(12)] = {
    [sym_source] = STATE(27),
    [sym__expression] = STATE(27),
    [sym_parenthesize] = STATE(27),
    [sym_multiplicative] = STATE(27),
    [sym_additive] = STATE(27),
    [sym_comparison] = STATE(27),
    [sym_logical] = STATE(27),
    [sym_assign] = STATE(27),
    [sym__number] = STATE(27),
    [sym_string_single_quoted] = STATE(27),
    [sym_string_double_quoted] = STATE(27),
    [sym__string] = STATE(27),
    [sym_numbers] = STATE(27),
    [sym_booleans] = STATE(27),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(65),
    [sym_number_octal] = ACTIONS(65),
    [sym_number_decimal] = ACTIONS(65),
    [sym_number_hex] = ACTIONS(65),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(65),
  },
  [STATE(13)] = {
    [sym_source] = STATE(29),
    [sym__expression] = STATE(29),
    [sym_parenthesize] = STATE(29),
    [sym_multiplicative] = STATE(29),
    [sym_additive] = STATE(29),
    [sym_comparison] = STATE(29),
    [sym_logical] = STATE(29),
    [sym_assign] = STATE(29),
    [sym__number] = STATE(29),
    [sym_string_single_quoted] = STATE(29),
    [sym_string_double_quoted] = STATE(29),
    [sym__string] = STATE(29),
    [sym_numbers] = STATE(29),
    [sym_booleans] = STATE(29),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_operator_add] = ACTIONS(9),
    [sym_operator_subtract] = ACTIONS(9),
    [sym_number_binary] = ACTIONS(67),
    [sym_number_octal] = ACTIONS(67),
    [sym_number_decimal] = ACTIONS(67),
    [sym_number_hex] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_numbers_zero] = ACTIONS(17),
    [sym_booleans_false] = ACTIONS(19),
    [sym_booleans_true] = ACTIONS(19),
    [sym_identifier] = ACTIONS(67),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(71), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(69), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [23] = 2,
    ACTIONS(75), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(73), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [46] = 2,
    ACTIONS(79), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(77), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [69] = 3,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(85), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(81), 12,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [94] = 2,
    ACTIONS(89), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(87), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [117] = 2,
    ACTIONS(93), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(91), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [140] = 2,
    ACTIONS(97), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(95), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [163] = 2,
    ACTIONS(101), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(99), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [186] = 3,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(105), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(103), 12,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [211] = 2,
    ACTIONS(109), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(107), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [234] = 2,
    ACTIONS(113), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(111), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [257] = 6,
    ACTIONS(123), 1,
      sym_assign_variable,
    ACTIONS(117), 2,
      sym_operator_add,
      sym_operator_subtract,
    ACTIONS(121), 2,
      sym_operator_less_than,
      sym_operator_greater_than,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(119), 4,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
    ACTIONS(115), 6,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [288] = 2,
    ACTIONS(127), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(125), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [311] = 4,
    ACTIONS(117), 2,
      sym_operator_add,
      sym_operator_subtract,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(131), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(129), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [338] = 7,
    ACTIONS(123), 1,
      sym_assign_variable,
    ACTIONS(133), 1,
      sym_operator_and,
    ACTIONS(117), 2,
      sym_operator_add,
      sym_operator_subtract,
    ACTIONS(121), 2,
      sym_operator_less_than,
      sym_operator_greater_than,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(119), 4,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
    ACTIONS(115), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_or,
      sym_assign_constant,
  [371] = 9,
    ACTIONS(133), 1,
      sym_operator_and,
    ACTIONS(137), 1,
      sym_operator_or,
    ACTIONS(139), 1,
      sym_assign_constant,
    ACTIONS(141), 1,
      sym_assign_variable,
    ACTIONS(117), 2,
      sym_operator_add,
      sym_operator_subtract,
    ACTIONS(121), 2,
      sym_operator_less_than,
      sym_operator_greater_than,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(135), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(119), 4,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
  [408] = 2,
    ACTIONS(145), 3,
      sym_operator_less_than,
      sym_operator_greater_than,
      sym_assign_variable,
    ACTIONS(143), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
      sym_operator_add,
      sym_operator_subtract,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
      sym_operator_and,
      sym_operator_or,
      sym_assign_constant,
  [431] = 9,
    ACTIONS(133), 1,
      sym_operator_and,
    ACTIONS(137), 1,
      sym_operator_or,
    ACTIONS(139), 1,
      sym_assign_constant,
    ACTIONS(141), 1,
      sym_assign_variable,
    ACTIONS(117), 2,
      sym_operator_add,
      sym_operator_subtract,
    ACTIONS(121), 2,
      sym_operator_less_than,
      sym_operator_greater_than,
    ACTIONS(147), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(119), 4,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
  [467] = 2,
    ACTIONS(21), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_operator_add,
      sym_operator_subtract,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
    ACTIONS(149), 8,
      sym_number_binary,
      sym_number_octal,
      sym_number_decimal,
      sym_number_hex,
      sym_numbers_zero,
      sym_booleans_false,
      sym_booleans_true,
      sym_identifier,
  [488] = 9,
    ACTIONS(133), 1,
      sym_operator_and,
    ACTIONS(137), 1,
      sym_operator_or,
    ACTIONS(139), 1,
      sym_assign_constant,
    ACTIONS(141), 1,
      sym_assign_variable,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(117), 2,
      sym_operator_add,
      sym_operator_subtract,
    ACTIONS(121), 2,
      sym_operator_less_than,
      sym_operator_greater_than,
    ACTIONS(83), 3,
      sym_operator_multiply,
      sym_operator_divide,
      sym_operator_modulo,
    ACTIONS(119), 4,
      sym_operator_equal,
      sym_operator_not_equal,
      sym_operator_less_equal,
      sym_operator_greater_equal,
  [523] = 3,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_string_double_quoted_repeat1,
    ACTIONS(153), 2,
      sym_escape,
      sym_string_double_quoted_unescaped_string,
  [534] = 3,
    ACTIONS(159), 1,
      anon_sym_SQUOTE,
    STATE(38), 1,
      aux_sym_string_single_quoted_repeat1,
    ACTIONS(157), 2,
      sym_escape,
      sym_string_single_quoted_unescaped_string,
  [545] = 3,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      aux_sym_string_double_quoted_repeat1,
    ACTIONS(161), 2,
      sym_escape,
      sym_string_double_quoted_unescaped_string,
  [556] = 3,
    ACTIONS(167), 1,
      anon_sym_SQUOTE,
    STATE(35), 1,
      aux_sym_string_single_quoted_repeat1,
    ACTIONS(165), 2,
      sym_escape,
      sym_string_single_quoted_unescaped_string,
  [567] = 3,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    STATE(38), 1,
      aux_sym_string_single_quoted_repeat1,
    ACTIONS(169), 2,
      sym_escape,
      sym_string_single_quoted_unescaped_string,
  [578] = 3,
    ACTIONS(177), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_string_double_quoted_repeat1,
    ACTIONS(174), 2,
      sym_escape,
      sym_string_double_quoted_unescaped_string,
  [589] = 2,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
  [596] = 2,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(179), 1,
      anon_sym_SEMI,
  [603] = 1,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
  [607] = 1,
    ACTIONS(179), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 23,
  [SMALL_STATE(16)] = 46,
  [SMALL_STATE(17)] = 69,
  [SMALL_STATE(18)] = 94,
  [SMALL_STATE(19)] = 117,
  [SMALL_STATE(20)] = 140,
  [SMALL_STATE(21)] = 163,
  [SMALL_STATE(22)] = 186,
  [SMALL_STATE(23)] = 211,
  [SMALL_STATE(24)] = 234,
  [SMALL_STATE(25)] = 257,
  [SMALL_STATE(26)] = 288,
  [SMALL_STATE(27)] = 311,
  [SMALL_STATE(28)] = 338,
  [SMALL_STATE(29)] = 371,
  [SMALL_STATE(30)] = 408,
  [SMALL_STATE(31)] = 431,
  [SMALL_STATE(32)] = 467,
  [SMALL_STATE(33)] = 488,
  [SMALL_STATE(34)] = 523,
  [SMALL_STATE(35)] = 534,
  [SMALL_STATE(36)] = 545,
  [SMALL_STATE(37)] = 556,
  [SMALL_STATE(38)] = 567,
  [SMALL_STATE(39)] = 578,
  [SMALL_STATE(40)] = 589,
  [SMALL_STATE(41)] = 596,
  [SMALL_STATE(42)] = 603,
  [SMALL_STATE(43)] = 607,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_double_quoted, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_double_quoted, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_double_quoted, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_double_quoted, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numbers, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numbers, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_additive, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_single_quoted, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_single_quoted, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_booleans, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_booleans, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_additive, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesize, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesize, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_single_quoted, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_single_quoted, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicative, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplicative, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_single_quoted_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_single_quoted_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_double_quoted_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_double_quoted_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [183] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mage(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mage",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 8,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
