/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym_string = 3,
  sym_zero = 4,
  sym_binary = 5,
  sym_octal = 6,
  sym_decimal = 7,
  sym_hex = 8,
  anon_sym_PLUS = 9,
  anon_sym_DASH = 10,
  anon_sym_STAR = 11,
  anon_sym_SLASH = 12,
  anon_sym_PERCENT = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym_name = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DOT = 20,
  anon_sym_COLON = 21,
  anon_sym_EQ = 22,
  anon_sym_SEMI = 23,
  sym_source_file = 24,
  sym_source = 25,
  sym_number = 26,
  sym_math_operation = 27,
  sym_math = 28,
  sym_call = 29,
  sym_identifier_chain = 30,
  sym_identifier = 31,
  sym_definition_operation = 32,
  sym_definition = 33,
  sym_statement_chain = 34,
  sym_statement = 35,
  aux_sym_math_repeat1 = 36,
  aux_sym_call_repeat1 = 37,
  aux_sym_identifier_chain_repeat1 = 38,
  aux_sym_definition_repeat1 = 39,
  aux_sym_statement_chain_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_string] = "string",
  [sym_zero] = "zero",
  [sym_binary] = "binary",
  [sym_octal] = "octal",
  [sym_decimal] = "decimal",
  [sym_hex] = "hex",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_name] = "name",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym_source] = "source",
  [sym_number] = "number",
  [sym_math_operation] = "math_operation",
  [sym_math] = "math",
  [sym_call] = "call",
  [sym_identifier_chain] = "identifier_chain",
  [sym_identifier] = "identifier",
  [sym_definition_operation] = "definition_operation",
  [sym_definition] = "definition",
  [sym_statement_chain] = "statement_chain",
  [sym_statement] = "statement",
  [aux_sym_math_repeat1] = "math_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_identifier_chain_repeat1] = "identifier_chain_repeat1",
  [aux_sym_definition_repeat1] = "definition_repeat1",
  [aux_sym_statement_chain_repeat1] = "statement_chain_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_string] = sym_string,
  [sym_zero] = sym_zero,
  [sym_binary] = sym_binary,
  [sym_octal] = sym_octal,
  [sym_decimal] = sym_decimal,
  [sym_hex] = sym_hex,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_name] = sym_name,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym_source] = sym_source,
  [sym_number] = sym_number,
  [sym_math_operation] = sym_math_operation,
  [sym_math] = sym_math,
  [sym_call] = sym_call,
  [sym_identifier_chain] = sym_identifier_chain,
  [sym_identifier] = sym_identifier,
  [sym_definition_operation] = sym_definition_operation,
  [sym_definition] = sym_definition,
  [sym_statement_chain] = sym_statement_chain,
  [sym_statement] = sym_statement,
  [aux_sym_math_repeat1] = aux_sym_math_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_identifier_chain_repeat1] = aux_sym_identifier_chain_repeat1,
  [aux_sym_definition_repeat1] = aux_sym_definition_repeat1,
  [aux_sym_statement_chain_repeat1] = aux_sym_statement_chain_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_octal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_math_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_math] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_definition_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_math_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 1,
        '%', 16,
        '(', 24,
        ')', 26,
        '*', 14,
        '+', 12,
        ',', 25,
        '-', 13,
        '.', 27,
        '/', 15,
        '0', 7,
        ':', 28,
        ';', 30,
        '=', 29,
        '[', 17,
        ']', 18,
        '{', 4,
        '}', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_zero);
      ADVANCE_MAP(
        'B', 19,
        'b', 19,
        'D', 21,
        'd', 21,
        'O', 20,
        'o', 20,
        'X', 22,
        'x', 22,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_binary);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(8);
      if (('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_octal);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(9);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(8);
      if (('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(9);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_zero] = ACTIONS(1),
    [sym_binary] = ACTIONS(1),
    [sym_octal] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [sym_hex] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(46),
    [sym_source] = STATE(32),
    [sym_math] = STATE(32),
    [sym_call] = STATE(6),
    [sym_identifier_chain] = STATE(22),
    [sym_identifier] = STATE(3),
    [sym_definition] = STATE(32),
    [sym_statement_chain] = STATE(47),
    [sym_statement] = STATE(37),
    [aux_sym_definition_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_string] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_name] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(19), 1,
      sym_math_operation,
    STATE(21), 1,
      aux_sym_math_repeat1,
    STATE(20), 2,
      sym_number,
      sym_identifier_chain,
    ACTIONS(13), 5,
      sym_zero,
      sym_binary,
      sym_octal,
      sym_decimal,
      sym_hex,
    ACTIONS(15), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [37] = 4,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_identifier_chain_repeat1,
    ACTIONS(21), 13,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [62] = 3,
    ACTIONS(25), 1,
      anon_sym_DOT,
    STATE(9), 1,
      aux_sym_identifier_chain_repeat1,
    ACTIONS(27), 13,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [84] = 1,
    ACTIONS(29), 15,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [102] = 1,
    ACTIONS(31), 15,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [120] = 1,
    ACTIONS(33), 15,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [138] = 2,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [158] = 3,
    ACTIONS(37), 1,
      anon_sym_DOT,
    STATE(9), 1,
      aux_sym_identifier_chain_repeat1,
    ACTIONS(35), 13,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [180] = 1,
    ACTIONS(40), 15,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_SEMI,
  [198] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(17), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(40), 1,
      sym_statement,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [235] = 12,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(17), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(37), 1,
      sym_statement,
    STATE(48), 1,
      sym_statement_chain,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [274] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(17), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(40), 1,
      sym_statement,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [311] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(17), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(42), 1,
      sym_statement,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [347] = 10,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      sym_string,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(15), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(30), 1,
      sym_statement,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [380] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(17), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(45), 1,
      sym_statement,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [413] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(15), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(30), 1,
      sym_statement,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [446] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_string,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(17), 1,
      aux_sym_definition_repeat1,
    STATE(22), 1,
      sym_identifier_chain,
    STATE(40), 1,
      sym_statement,
    STATE(32), 3,
      sym_source,
      sym_math,
      sym_definition,
  [479] = 5,
    ACTIONS(19), 1,
      sym_name,
    STATE(3), 1,
      sym_identifier,
    STATE(6), 1,
      sym_call,
    STATE(27), 2,
      sym_number,
      sym_identifier_chain,
    ACTIONS(13), 5,
      sym_zero,
      sym_binary,
      sym_octal,
      sym_decimal,
      sym_hex,
  [500] = 4,
    ACTIONS(62), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_math_operation,
    STATE(24), 1,
      aux_sym_math_repeat1,
    ACTIONS(15), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [517] = 4,
    ACTIONS(62), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_math_operation,
    STATE(23), 1,
      aux_sym_math_repeat1,
    ACTIONS(15), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [534] = 3,
    STATE(36), 1,
      sym_definition_operation,
    ACTIONS(66), 2,
      anon_sym_COLON,
      anon_sym_EQ,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [549] = 4,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_math_operation,
    STATE(23), 1,
      aux_sym_math_repeat1,
    ACTIONS(68), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [566] = 4,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_math_operation,
    STATE(23), 1,
      aux_sym_math_repeat1,
    ACTIONS(15), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [583] = 1,
    ACTIONS(75), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [592] = 1,
    ACTIONS(77), 6,
      sym_zero,
      sym_binary,
      sym_octal,
      sym_decimal,
      sym_hex,
      sym_name,
  [601] = 1,
    ACTIONS(71), 6,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [610] = 1,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [618] = 1,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [626] = 1,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [634] = 1,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [642] = 1,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [650] = 1,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [658] = 1,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [666] = 3,
    ACTIONS(93), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      aux_sym_statement_chain_repeat1,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [677] = 1,
    ACTIONS(96), 4,
      anon_sym_LBRACE,
      sym_string,
      anon_sym_LBRACK,
      sym_name,
  [684] = 3,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      aux_sym_statement_chain_repeat1,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [695] = 3,
    ACTIONS(102), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      aux_sym_statement_chain_repeat1,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [706] = 1,
    ACTIONS(104), 4,
      anon_sym_LBRACE,
      sym_string,
      anon_sym_LBRACK,
      sym_name,
  [713] = 1,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [719] = 3,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_call_repeat1,
  [729] = 3,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_call_repeat1,
  [739] = 3,
    ACTIONS(11), 1,
      sym_name,
    STATE(6), 1,
      sym_call,
    STATE(8), 1,
      sym_identifier,
  [749] = 3,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_call_repeat1,
  [759] = 1,
    ACTIONS(109), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [764] = 1,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
  [768] = 1,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
  [772] = 1,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 138,
  [SMALL_STATE(9)] = 158,
  [SMALL_STATE(10)] = 180,
  [SMALL_STATE(11)] = 198,
  [SMALL_STATE(12)] = 235,
  [SMALL_STATE(13)] = 274,
  [SMALL_STATE(14)] = 311,
  [SMALL_STATE(15)] = 347,
  [SMALL_STATE(16)] = 380,
  [SMALL_STATE(17)] = 413,
  [SMALL_STATE(18)] = 446,
  [SMALL_STATE(19)] = 479,
  [SMALL_STATE(20)] = 500,
  [SMALL_STATE(21)] = 517,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 549,
  [SMALL_STATE(24)] = 566,
  [SMALL_STATE(25)] = 583,
  [SMALL_STATE(26)] = 592,
  [SMALL_STATE(27)] = 601,
  [SMALL_STATE(28)] = 610,
  [SMALL_STATE(29)] = 618,
  [SMALL_STATE(30)] = 626,
  [SMALL_STATE(31)] = 634,
  [SMALL_STATE(32)] = 642,
  [SMALL_STATE(33)] = 650,
  [SMALL_STATE(34)] = 658,
  [SMALL_STATE(35)] = 666,
  [SMALL_STATE(36)] = 677,
  [SMALL_STATE(37)] = 684,
  [SMALL_STATE(38)] = 695,
  [SMALL_STATE(39)] = 706,
  [SMALL_STATE(40)] = 713,
  [SMALL_STATE(41)] = 719,
  [SMALL_STATE(42)] = 729,
  [SMALL_STATE(43)] = 739,
  [SMALL_STATE(44)] = 749,
  [SMALL_STATE(45)] = 759,
  [SMALL_STATE(46)] = 764,
  [SMALL_STATE(47)] = 768,
  [SMALL_STATE(48)] = 772,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_chain, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_chain, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_chain_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_chain_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_chain, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_chain, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0), SHIFT(12),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0), SHIFT(32),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0), SHIFT(2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0), SHIFT(6),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_math_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_math_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_operation, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_chain_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_chain_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_chain, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_operation, 1, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [117] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mage(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mage",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
